language: objective-c
xcode_project: Decodable.xcodeproj # path to your xcodeproj folder
osx_image: xcode8
script:
  - xcodebuild test -project Decodable.xcodeproj/ -scheme 'Decodable-iOS' -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'
  -  xcodebuild test -project Decodable.xcodeproj/ -scheme 'Decodable-Mac' ONLY_ACTIVE_ARCH=NO

